### ISSUE TITLE
mvp: DASing timeouts on the second API call after a 5min wait

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/lazyledger-core#391]
> NOTE: everything works in case waiting time is shorter

Currently, our MVP flow is straightforward:
1. Spin up a full node
2. Connect light client to it along with subjective initialization(`height=1`)
3. Start DASing through API by requesting block(`hegiht=15`)

The flow works flawlessly and the light client is able to find the full node on the IPFS network in 1-5 secs along with first block validation(`height=1`). All the subsequent blocks(`height=2-15`) are validated in 200-300ms until the one requested through(`height=15`) an API. Also, further API requests(`height=30,45`) go well and validated in a short time. However, in case a request is fired ~5min after the previous one, DASing starts to timeout, and only restart of the light client helps. Time is approximate, but usually, I wait a lot to repeat the behavior, and if I do it too early everything works smoothly.

**Comment by Wondertan** [comment]
I spent some time on this already, but it is not obvious to me why this happens. The thing I am sure about is that it is somewhere on the Bitswap configuration level and perhaps connected with session longliveness.

**Comment by Wondertan** [comment]
I think that for now I will live that as it is and tackle it in the nearest future along with block propagation implementation. If there is an issue here, it should probably shoot again somewhere on consensus level as well.

**Comment by liamsi** [comment]
>  However, in case a request is fired ~5min after the previous one, DASing starts to timeout, and only restart of the light client helps. Time is approximate, but usually, I wait a lot to repeat the behavior, and if I do it too early everything works smoothly.

Thanks for this summary 🙏🏼  Just to confirm, is this on master or on your branch? 

> so I guess this does not have a high priority.

Yeah, let's focus on the ADR and come back to this shortly after that though.

**Comment by Wondertan** [comment]
On my branch, but I am quite sure that master would have similar behavior

**Comment by liamsi** [comment]
@Wondertan @evan-forbes I think we can close this, right? We understood that we were essentially creating blocks too fast s.t. providing (especially prior Hlib's changes) couldn't ever catch up. The near term work-around is to explicitly connect to a node that will have the data (similarly to light clients in tendermint need to be provided with an RPC addr of a full node). Later we will implement peer discovery via gossiping / pex / dht (but on much more coarse level and if we can't find the data otherwise). but this requires further investigation. 

Feel free to re-open if this requires further clarification.
